const ADD_FOOD = 'ADD_FOOD';
const REMOVE_FOOD = 'REMOVE_FOOD';
const SELECT_FOOD = 'SELECT_FOOD';


exports.ADD_FOOD = ADD_FOOD;
exports.SELECT_FOOD = SELECT_FOOD;
exports.REMOVE_FOOD = REMOVE_FOOD;
